# Generated by Django 5.2.8 on 2025-11-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('source', models.URLField()),
                ('tags', models.ManyToManyField(blank=True, to='dua_collection.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], max_length=50)),
                ('text', models.TextField()),
                ('dua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dua_collection.dua')),
            ],
        ),
    ]
